language: python

# sbam needs to be run as root
sudo: required

python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "nightly" # currently points to 3.6-dev

# command to install dependencies
install:
  - sudo pip install --upgrade pip
  - sudo pip install nose
  - sudo pip install -r requirements.txt

# command to run tests
script: sudo nosetests
